version: "3"

services:
  web-client:
    build:
      context: ../services/web-client
      dockerfile: ./Dockerfile.dev
    restart: always
    ports:
      - "3001:3001"

  server:
    build:
      context: ../services/server
      dockerfile: ./Dockerfile.dev
    restart: always
    environment:
      - PORT=3000
      - ALLOWED_ORIGIN=http://localhost:3001
    ports:
      - "3000:3000"

