version: "3.8"

services:
  web-client:
    build:
      context: ../services
      dockerfile: web-client/Dockerfile.dev
    restart: always
    volumes:
      - "../services/web-client:/app"
    ports:
      - "3001:3001"

  server:
    build:
      context: ../services
      dockerfile: server/Dockerfile.dev
    restart: always
    volumes:
      - "../services/server:/app"
    ports:
      - "3000:3000"

